name: Linked list

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: | 
          cd linked-list
          go mod verify

      - name: Run tests
        run: |
          cd linked-list
          go test -race -vet=off ./...